### ISSUE TITLE
Expected to decode Dictionary<String, Any> but found a string/data instead.

### ISSUE THREAD

**Issue by jriosdev** [GetStream/stream-swift#19]
## What did you do?
while activity fetching

`self.timelineFeed?.get(enrich: true, pagination: .limit(limit) + .offset(offset), ranking: nil, 
   includeReactions: .all, completion: { feedsResults in
            do{
                self.timelinePosts =  try feedsResults.get().results
            } catch {
            }
        })
`
## What happened instead?
getting 
JSON decoding error: The data couldn’t be read because it isn’t in the correct format.. Data: 5901 bytes
  ▿ jsonDecode : 3 elements
    - .0 : "The data couldn’t be read because it isn’t in the correct format."
    ▿ .1 : Optional<Error>
      ▿ some : DecodingError
        ▿ typeMismatch : 2 elements
          - .0 : Swift.Dictionary<Swift.String, Any>
          ▿ .1 : Context
            ▿ codingPath : 3 elements
              - 0 : CodingKeys(stringValue: "results", intValue: nil)
              ▿ 1 : _JSONKey(stringValue: "Index 0", intValue: 0)
                - stringValue : "Index 0"
                ▿ intValue : Optional<Int>
                  - some : 0
              - 2 : CodingKeys(stringValue: "actor", intValue: nil)
            - debugDescription : "Expected to decode Dictionary<String, Any> but found a string/data instead."
            - underlyingError : nil
    ▿ .2 : 5901 bytes
      - count : 5901
      ▿ pointer : 0x00007ff0e1127200
        - pointerValue : 140672544961024

## GetStream Environment
**GetStream version:2.2.1**
**Xcode version:11**
**Swift version:5**
**Platform(s) running GetStream:iOS**
**macOS version running Xcode:10.15**

## Additional context

the error happening inside
`
func parse<T: Decodable>(_ callbackQueue: DispatchQueue, _ completion: @escaping CompletionObjects<T>) {
        parse(block: {
            let moyaResponse = try get()
            var response = try JSONDecoder.default.decode(Response<T>.self, from: moyaResponse.data)
            if let next = response.next, case .none = next {
                response.next = nil
            }
            callbackQueue.async { completion(.success(response)) }
        }, catch: { error in
            callbackQueue.async { completion(.failure(error)) }
        })
    }
`

**Comment by b-onc** [comment]
Hey @jriosdev ,

Can you enable and post logs, with `Client.config = .init(apiKey: "...", appId: "...", logsEnabled: true)`

**Comment by jriosdev** [comment]
already enabled, the  activity result array is printing 
but the closure FlatFeed.get() return error  
"The data couldn’t be read because it isn’t in the correct format."

**Comment by buh** [comment]
Hi @jriosdev 
Can you show your `Activity` type that you use in your `timelineFeed`?
So, basically you use enrichment (`enrich: true`) and Activity by default use a `User` as an actor. The error occurs because the JSON data has a string instead of a user JSON for the actor field. Can you show the response from logs?

**Comment by jriosdev** [comment]
thank u fixed

**Comment by SRReddy411** [comment]
@jriosdev  how you resolve the above issue  i am also facing same but i have try many ways still i am getting same error.
thank you
