### ISSUE TITLE
Upgrade GetStream Library to use Moya 14

### ISSUE THREAD

**Issue by JoeCotellese** [GetStream/stream-swift#25]
## What did you do?
Tried to build my app with the GetStream library

## What did you expect to happen?
I could run pod install and everything worked correctly.

## What happened instead?
I received an error because my app uses Alamofire 5

I did some searching in the Moya project. The latest version works with Alamofire 5
## GetStream Environment
**GetStream version:**
2.2.2

**Comment by b-onc** [comment]
Hello @JoeCotellese 

As I see, on a fresh project GetStream 2.2.2 uses Alamofire 5.1 and Moya 14. What is the error you're receiving?

**Comment by b-onc** [comment]
Hello @Parithi 
I've opened PR #28, can you test that branch and let me know if it works?

**Comment by AndrewRudyk** [comment]
I have same problem:
Alamofire (~> 5.1)
GetStreamActivityFeed (~> 2.2)

And terminal error:
pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (= 5.2.0, ~> 5.2)

  In Podfile:
    Alamofire (~> 5.1)

    GetStreamActivityFeed (~> 2.2) was resolved to 2.2.1, which depends on
      GetStream (~> 2.2) was resolved to 2.2.0, which depends on
        GetStream/Core (= 2.2.0) was resolved to 2.2.0, which depends on
          Moya (~> 13.0) was resolved to 13.0.0, which depends on
            Moya/Core (= 13.0.0) was resolved to 13.0.0, which depends on
              Alamofire (~> 4.1)
