### ISSUE TITLE
Getting parsing error when trying to fetch a single activity

### ISSUE THREAD

**Issue by deepak-vishwakarma-spok** [GetStream/stream-swift#8]
When I m trying to fetch a activity , parsing getting failed.
Below is the error :
GetStream.ClientError.jsonDecode("The data couldn’t be read because it isn’t in the correct format.", Optional(Swift.DecodingError.typeMismatch(Swift.Dictionary, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "actor", intValue: nil)], debugDescription: "Expected to decode Dictionary but found a string/data instead.", underlyingError: nil)))

**Comment by deepak-vishwakarma-spok** [comment]
When I m trying to fetch a activity , parsing getting failed. 
Below is the error : 
GetStream.ClientError.jsonDecode("The data couldn’t be read because it isn’t in the correct format.", Optional(Swift.DecodingError.typeMismatch(Swift.Dictionary, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "actor", intValue: nil)], debugDescription: "Expected to decode Dictionary but found a string/data instead.", underlyingError: nil)))

**Comment by buh** [comment]
Hey @deepak-vishwakarma-spok!
Could you show me your code with the request?

**Comment by buh** [comment]
@deepak-vishwakarma-spok 
I think I found the problem, if your `Activity.actor` is a `User`, then the request can't decoded to it, because the enrich parameter is missed. I'll fix it soon and let you know.

**Comment by buh** [comment]
Fixed. Please check the new version 1.2.0
